# Generated by Django 6.0.3 on 2026-03-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin (SuperAdmin)'), ('MANAGER', "Manager (Bo'lim boshlig'i)"), ('EMPLOYEE', 'Employee (Xodim)')], default='EMPLOYEE', max_length=10),
        ),
    ]
