# Generated by Django 6.0.3 on 2026-03-20 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_remove_exam_passing_percent_exam_passing_score'),
        ('users', '0004_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_employees', to='exams.exam'),
        ),
    ]
