# Generated by Django 6.0.3 on 2026-03-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='passing_percent',
        ),
        migrations.AddField(
            model_name='exam',
            name='passing_score',
            field=models.IntegerField(default=35, help_text="O'tish uchun minimal to'g'ri javoblar soni (masalan: 35)"),
        ),
    ]
